### ISSUE TITLE
Scraping tagged StackOverflow free text

### ISSUE THREAD

**Issue by pitukg** [tbarker2001/agile-computing-gp#2]
Need a Python script scraping StackOverflow discussions in a subset of tags, and writing it to a text file.
Produce a document of the tags selected.
Tags need the prefix `__label__` to be processed by Fasttext.

**Comment by TechTurtle11** [comment]
Would it be possible for someone to add the __label__ prefix when writing StackOverflow tags not exactly sure what format is wanted.
